"""schema initial campagne (21 tables)

Revision ID: 042ca25b388b
Revises: 
Create Date: 2026-06-29 22:00:53.526084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042ca25b388b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('nationalite', sa.String(length=64), nullable=True),
    sa.Column('pays_residence', sa.String(length=64), nullable=True),
    sa.Column('est_personne_physique', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('municipale', 'metropole', 'secteur', 'legislative', 'departementale', 'regionale', 'europeenne', 'autre', name='typeelection', native_enum=False, length=32), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('circonscription', sa.String(length=255), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('date_tour1', sa.Date(), nullable=True),
    sa.Column('date_tour2', sa.Date(), nullable=True),
    sa.Column('plafond_depenses', sa.Float(), nullable=True),
    sa.Column('date_limite_depot', sa.Date(), nullable=True),
    sa.Column('date_cloture_compte', sa.Date(), nullable=True),
    sa.Column('date_depot_surcharge', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partie_externe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom_ou_liste', sa.String(length=255), nullable=True),
    sa.Column('scrutin', sa.String(length=120), nullable=True),
    sa.Column('circonscription', sa.String(length=255), nullable=True),
    sa.Column('mandataire_contact', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carnet_recus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('numero_carnet', sa.String(length=64), nullable=False),
    sa.Column('numero_formule_debut', sa.Integer(), nullable=False),
    sa.Column('numero_formule_fin', sa.Integer(), nullable=False),
    sa.Column('date_retrait_prefecture', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('echeance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('date_cible', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=32), nullable=True),
    sa.Column('regle_calcul', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('reunion_publique', 'collecte', 'tractage', 'meeting', 'porte_a_porte', 'reception', 'autre', name='typeevenement', native_enum=False, length=32), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('facture', 'recu', 'releve_bancaire', 'recepisse', 'photo', 'contrat', 'statuts', 'autre', name='typedocument', native_enum=False, length=32), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('fichier', sa.String(length=512), nullable=False),
    sa.Column('enveloppe', sa.Enum('A', 'B', 'hors_depot', name='enveloppe', native_enum=False, length=32), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_financement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination', sa.String(length=255), nullable=False),
    sa.Column('siege_social', sa.String(length=255), nullable=True),
    sa.Column('date_declaration_prefecture', sa.Date(), nullable=True),
    sa.Column('date_publication_jo', sa.Date(), nullable=True),
    sa.Column('statuts_doc_id', sa.Integer(), nullable=True),
    sa.Column('president_identite', sa.String(length=255), nullable=True),
    sa.Column('tresorier_identite', sa.String(length=255), nullable=True),
    sa.Column('delib_bureau_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delib_bureau_doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['statuts_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('civilite', sa.String(length=16), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('nom_usage', sa.String(length=120), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('tete_de_liste', sa.Boolean(), nullable=False),
    sa.Column('adresse_postale', sa.String(length=255), nullable=True),
    sa.Column('code_postal', sa.String(length=16), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('adresse_post_campagne', sa.String(length=255), nullable=True),
    sa.Column('remplacant_identite', sa.String(length=255), nullable=True),
    sa.Column('recepisse_candidature_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['recepisse_candidature_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concours_nature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('origine', sa.Enum('candidat', 'parti', 'tiers_pp', name='origineconcours', native_enum=False, length=32), nullable=False),
    sa.Column('nature', sa.String(length=255), nullable=False),
    sa.Column('valeur_estimee', sa.Float(), nullable=False),
    sa.Column('methode_evaluation', sa.Text(), nullable=True),
    sa.Column('rubrique_imputation', sa.String(length=32), nullable=True),
    sa.Column('justificatif_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['justificatif_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('date_signature', sa.Date(), nullable=True),
    sa.Column('document_genere_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_genere_doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_comptable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('dispense', sa.Boolean(), nullable=False),
    sa.Column('cabinet', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('adresse_postale', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('date_designation', sa.Date(), nullable=True),
    sa.Column('lettre_mission_doc_id', sa.Integer(), nullable=True),
    sa.Column('mission_etendue', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['lettre_mission_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenement_concours',
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('concours_id', sa.Integer(), nullable=False),
    sa.Column('quote_part', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concours_id'], ['concours_nature.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.PrimaryKeyConstraint('evenement_id', 'concours_id')
    )
    op.create_table('mandataire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('physique', 'afe', name='typemandataire', native_enum=False, length=32), nullable=False),
    sa.Column('civilite', sa.String(length=16), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('adresse_postale', sa.String(length=255), nullable=True),
    sa.Column('code_postal', sa.String(length=16), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('date_declaration_prefecture', sa.Date(), nullable=True),
    sa.Column('prefecture', sa.String(length=120), nullable=True),
    sa.Column('recepisse_doc_id', sa.Integer(), nullable=True),
    sa.Column('accord_expres_doc_id', sa.Integer(), nullable=True),
    sa.Column('incompatibilites_verifiees', sa.Boolean(), nullable=False),
    sa.Column('capacite_civile_ok', sa.Boolean(), nullable=False),
    sa.Column('interdiction_bancaire', sa.Boolean(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accord_expres_doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['association_id'], ['association_financement.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['recepisse_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compte_bancaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandataire_id', sa.Integer(), nullable=False),
    sa.Column('banque', sa.String(length=120), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=40), nullable=True),
    sa.Column('date_ouverture', sa.Date(), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('droit_au_compte_active', sa.Boolean(), nullable=False),
    sa.Column('preuves_difficultes_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mandataire_id'], ['mandataire.id'], ),
    sa.ForeignKeyConstraint(['preuves_difficultes_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('nature', sa.String(length=255), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('date_reglement', sa.Date(), nullable=True),
    sa.Column('mode', sa.Enum('cheque', 'virement', 'cb', 'prelevement', 'especes', 'plateforme', name='modepaiement', native_enum=False, length=32), nullable=True),
    sa.Column('num_releve_bancaire', sa.String(length=64), nullable=True),
    sa.Column('num_piece', sa.String(length=64), nullable=True),
    sa.Column('rubrique_imputation', sa.String(length=32), nullable=False),
    sa.Column('facture_doc_id', sa.Integer(), nullable=True),
    sa.Column('type_support', sa.Enum('tract', 'affiche', 'flyer', 'location_salle', 'prestation', 'impression', 'communication', 'deplacement', 'autre', name='typesupport', native_enum=False, length=32), nullable=True),
    sa.Column('statut', sa.Enum('engage', 'facture', 'paye', 'realise_nature', name='statutdepense', native_enum=False, length=32), nullable=False),
    sa.Column('reglee', sa.Boolean(), nullable=False),
    sa.Column('cheque_encaisse', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['compte_bancaire.id'], ),
    sa.ForeignKeyConstraint(['facture_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=True),
    sa.Column('donateur_id', sa.Integer(), nullable=True),
    sa.Column('categorie', sa.Enum('don', 'apport_perso', 'pret', 'contribution_parti', 'produit_divers', 'collecte', name='categorierecette', native_enum=False, length=32), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_versement', sa.Date(), nullable=False),
    sa.Column('mode', sa.Enum('cheque', 'virement', 'cb', 'prelevement', 'especes', 'plateforme', name='modepaiement', native_enum=False, length=32), nullable=True),
    sa.Column('num_releve_bancaire', sa.String(length=64), nullable=True),
    sa.Column('num_piece', sa.String(length=64), nullable=True),
    sa.Column('rubrique_imputation', sa.String(length=32), nullable=False),
    sa.Column('justificatif_doc_id', sa.Integer(), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['compte_bancaire.id'], ),
    sa.ForeignKeyConstraint(['donateur_id'], ['donateur.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.ForeignKeyConstraint(['justificatif_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depense_mutualisee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('convention_id', sa.Integer(), nullable=True),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('evenement_id', sa.Integer(), nullable=True),
    sa.Column('montant_total_ttc', sa.Float(), nullable=False),
    sa.Column('cle_justification', sa.Text(), nullable=True),
    sa.Column('porteur', sa.Enum('notre_campagne', 'partie_externe', name='porteurmutualise', native_enum=False, length=32), nullable=False),
    sa.Column('porteur_partie_id', sa.Integer(), nullable=True),
    sa.Column('depense_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['convention_id'], ['convention.id'], ),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.ForeignKeyConstraint(['porteur_partie_id'], ['partie_externe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenement_depense',
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('depense_id', sa.Integer(), nullable=False),
    sa.Column('quote_part', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.PrimaryKeyConstraint('evenement_id', 'depense_id')
    )
    op.create_table('recu_don',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_formule', sa.Integer(), nullable=False),
    sa.Column('carnet_id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('delivre', 'annule', 'non_utilise', name='statutrecudon', native_enum=False, length=32), nullable=False),
    sa.Column('avantage_fiscal_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carnet_id'], ['carnet_recus.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carnet_id', 'numero_formule', name='uq_recu_carnet_formule')
    )
    op.create_table('repartition_mutualisee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depense_mutualisee_id', sa.Integer(), nullable=False),
    sa.Column('partie', sa.Enum('notre_campagne', 'partie_externe', name='partiemutualisee', native_enum=False, length=32), nullable=False),
    sa.Column('partie_id', sa.Integer(), nullable=True),
    sa.Column('pourcentage', sa.Float(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('statut_reglement', sa.Enum('du', 'percu', 'regle', 'sans_objet', name='statutreglementmutualise', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['depense_mutualisee_id'], ['depense_mutualisee.id'], ),
    sa.ForeignKeyConstraint(['partie_id'], ['partie_externe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repartition_mutualisee')
    op.drop_table('recu_don')
    op.drop_table('evenement_depense')
    op.drop_table('depense_mutualisee')
    op.drop_table('recette')
    op.drop_table('depense')
    op.drop_table('compte_bancaire')
    op.drop_table('mandataire')
    op.drop_table('evenement_concours')
    op.drop_table('expert_comptable')
    op.drop_table('convention')
    op.drop_table('concours_nature')
    op.drop_table('candidat')
    op.drop_table('association_financement')
    op.drop_table('document')
    op.drop_table('evenement')
    op.drop_table('echeance')
    op.drop_table('carnet_recus')
    op.drop_table('partie_externe')
    op.drop_table('election')
    op.drop_table('donateur')
    # ### end Alembic commands ###
