"""Colonne de prise en charge des dépenses (mandataire / parti).

Les dépenses existantes ont toutes été réglées par le mandataire : c'est la
seule prise en charge que l'application connaissait.

prise en charge des depenses

Revision ID: 0632cd0b9c70
Revises: a3eb00daabce
Create Date: 2026-09-25 08:39:01.806210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0632cd0b9c70'
down_revision: Union[str, Sequence[str], None] = 'a3eb00daabce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prise_en_charge', sa.Enum('mandataire', 'parti', name='priseencharge', native_enum=False, length=32), nullable=False, server_default='mandataire'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.drop_column('prise_en_charge')

    # ### end Alembic commands ###
