"""devolution de l excedent

Revision ID: 129c0fb66b13
Revises: 0632cd0b9c70
Create Date: 2026-09-25 08:42:26.486658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129c0fb66b13'
down_revision: Union[str, Sequence[str], None] = '0632cd0b9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('beneficiaire_type', sa.Enum('parti', 'association', 'fonds_vie_associative', name='beneficiairedevolution', native_enum=False, length=32), nullable=False),
    sa.Column('beneficiaire_nom', sa.String(length=255), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_decision', sa.Date(), nullable=True),
    sa.Column('justificatif_doc_id', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['justificatif_doc_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devolution')
    # ### end Alembic commands ###
