"""Traçabilité et validation des objets soumis au mandataire.

Les lignes existantes passent en `valide` : elles ont été saisies par le
mandataire lui-même et sont déjà dans le compte. Les faire naître « à valider »
les sortirait rétroactivement du plafond et de la trésorerie.

tracabilite et validation des objets soumis

Revision ID: 9e52f08ba74b
Revises: fd7c385c1c65
Create Date: 2026-09-23 18:16:54.801012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e52f08ba74b'
down_revision: Union[str, Sequence[str], None] = 'fd7c385c1c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depense_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'repondue', 'close', name='statutdemandepiece', native_enum=False, length=32), nullable=False),
    sa.Column('demande_par', sa.String(length=64), nullable=True),
    sa.Column('demande_le', sa.DateTime(), nullable=True),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('repondu_par', sa.String(length=64), nullable=True),
    sa.Column('repondu_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cree_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cree_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statut_validation', sa.Enum('valide', 'propose', 'refuse', name='statutvalidation', native_enum=False, length=32), nullable=False, server_default='valide'))
        batch_op.add_column(sa.Column('valide_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motif_refus', sa.Text(), nullable=True))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cree_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cree_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statut_validation', sa.Enum('valide', 'propose', 'refuse', name='statutvalidation', native_enum=False, length=32), nullable=False, server_default='valide'))
        batch_op.add_column(sa.Column('valide_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motif_refus', sa.Text(), nullable=True))

    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cree_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cree_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statut_validation', sa.Enum('valide', 'propose', 'refuse', name='statutvalidation', native_enum=False, length=32), nullable=False, server_default='valide'))
        batch_op.add_column(sa.Column('valide_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motif_refus', sa.Text(), nullable=True))

    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cree_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cree_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statut_validation', sa.Enum('valide', 'propose', 'refuse', name='statutvalidation', native_enum=False, length=32), nullable=False, server_default='valide'))
        batch_op.add_column(sa.Column('valide_par', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motif_refus', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_column('motif_refus')
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide_par')
        batch_op.drop_column('statut_validation')
        batch_op.drop_column('cree_le')
        batch_op.drop_column('cree_par')

    with op.batch_alter_table('evenement', schema=None) as batch_op:
        batch_op.drop_column('motif_refus')
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide_par')
        batch_op.drop_column('statut_validation')
        batch_op.drop_column('cree_le')
        batch_op.drop_column('cree_par')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('motif_refus')
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide_par')
        batch_op.drop_column('statut_validation')
        batch_op.drop_column('cree_le')
        batch_op.drop_column('cree_par')

    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.drop_column('motif_refus')
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide_par')
        batch_op.drop_column('statut_validation')
        batch_op.drop_column('cree_le')
        batch_op.drop_column('cree_par')

    op.drop_table('demande_piece')
    # ### end Alembic commands ###
