"""Relevés bancaires et rapprochement des dépenses.

`date_reglement` est renommée `date_facture` : elle contenait la date de la
facture, pas celle du débit. La date de paiement se lit désormais sur la
transaction bancaire rapprochée.

releves bancaires et rapprochement

Revision ID: a3eb00daabce
Revises: 9e52f08ba74b
Create Date: 2026-09-25 05:03:14.293916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3eb00daabce'
down_revision: Union[str, Sequence[str], None] = '9e52f08ba74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('csv', 'ocr', 'manuel', name='sourcereleve', native_enum=False, length=32), nullable=False),
    sa.Column('fichier', sa.String(length=512), nullable=True),
    sa.Column('importe_par', sa.String(length=64), nullable=True),
    sa.Column('importe_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['compte_bancaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_bancaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('releve_id', sa.Integer(), nullable=False),
    sa.Column('date_operation', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('sens', sa.Enum('debit', 'credit', name='senstransaction', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['releve_id'], ['releve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imputation_bancaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('depense_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['depense_id'], ['depense.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_bancaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depense', schema=None) as batch_op:
        # Renommage, pas un ajout suivi d'une suppression : la colonne porte
        # déjà les dates de facture de toutes les dépenses saisies.
        batch_op.alter_column('date_reglement', new_column_name='date_facture')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depense', schema=None) as batch_op:
        batch_op.alter_column('date_facture', new_column_name='date_reglement')

    op.drop_table('imputation_bancaire')
    op.drop_table('transaction_bancaire')
    op.drop_table('releve')
    # ### end Alembic commands ###
