"""ajoute champs compat donateur.adresse recette.recu_genere date_envoi

Revision ID: e60075afc8ec
Revises: 042ca25b388b
Create Date: 2026-06-29 22:30:07.288794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60075afc8ec'
down_revision: Union[str, Sequence[str], None] = '042ca25b388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))

    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recu_genere', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('date_envoi', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_column('date_envoi')
        batch_op.drop_column('recu_genere')

    with op.batch_alter_table('donateur', schema=None) as batch_op:
        batch_op.drop_column('adresse')

    # ### end Alembic commands ###
