"""annexes CNCCFP colistiers equipe emprunts champs journal identite

Revision ID: fd7c385c1c65
Revises: e60075afc8ec
Create Date: 2026-06-30 01:21:24.018983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7c385c1c65'
down_revision: Union[str, Sequence[str], None] = 'e60075afc8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colistier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('civilite', sa.String(length=16), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('mandat_parlementaire', sa.String(length=120), nullable=True),
    sa.Column('present_tour1', sa.Boolean(), nullable=False),
    sa.Column('present_tour2', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membre_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('fonction', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprunt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('banque', 'parti', 'personne_physique', name='typeemprunt', native_enum=False, length=32), nullable=False),
    sa.Column('preteur_nom', sa.String(length=255), nullable=True),
    sa.Column('preteur_civilite', sa.String(length=16), nullable=True),
    sa.Column('preteur_prenom', sa.String(length=120), nullable=True),
    sa.Column('preteur_pays', sa.String(length=64), nullable=True),
    sa.Column('date_contrat', sa.Date(), nullable=True),
    sa.Column('duree_mois', sa.Integer(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('taux', sa.Float(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('contrat_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrat_doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ADD COLUMN natif SQLite (pas de batch : évite la recréation de tables à FK
    # non nommées). Les booléens NOT NULL reçoivent un server_default.
    op.add_column('candidat', sa.Column('lieu_naissance', sa.String(length=120), nullable=True))
    op.add_column('candidat', sa.Column('mandat_parlementaire', sa.String(length=120), nullable=True))

    op.add_column('depense', sa.Column('num_cheque_remise', sa.String(length=64), nullable=True))
    op.add_column('depense', sa.Column('rapprochement', sa.Boolean(), nullable=False, server_default=sa.false()))

    op.add_column('donateur', sa.Column('code_postal', sa.String(length=16), nullable=True))
    op.add_column('donateur', sa.Column('ville', sa.String(length=120), nullable=True))

    op.add_column('election', sa.Column('nom_liste', sa.String(length=255), nullable=True))
    op.add_column('election', sa.Column('nuance_politique', sa.String(length=255), nullable=True))

    op.add_column('recette', sa.Column('num_cheque_remise', sa.String(length=64), nullable=True))
    op.add_column('recette', sa.Column('date_remise_banque', sa.Date(), nullable=True))
    op.add_column('recette', sa.Column('rapprochement', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('recette', sa.Column('emprunt_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for col in ('emprunt_id', 'rapprochement', 'date_remise_banque', 'num_cheque_remise'):
        op.drop_column('recette', col)
    for col in ('nuance_politique', 'nom_liste'):
        op.drop_column('election', col)
    for col in ('ville', 'code_postal'):
        op.drop_column('donateur', col)
    for col in ('rapprochement', 'num_cheque_remise'):
        op.drop_column('depense', col)
    for col in ('mandat_parlementaire', 'lieu_naissance'):
        op.drop_column('candidat', col)

    op.drop_table('emprunt')
    op.drop_table('membre_equipe')
    op.drop_table('colistier')
    # ### end Alembic commands ###
